const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { RobloxFile } = require("rbxm-parser");
const { parseConfig } = require("../src/config");
const { generateLuau, generateDts, buildTree, renderLuauType } = require("../src/codegen");
const { DEFAULT_CODEGEN_FORMAT, listCodegenFormats, registerCodegenFormat, resolveCodegenFormat } = require("../src/formats");
const { EXT_TO_ASSET_TYPE, syncOne, configFingerprint, planSyncAction, fileHash } = require("../src/sync");
const { contentTypeFor } = require("../src/upload");
const { buildAssetMap, lockPathForSync } = require("../src/asset-map");
const {
	buildStudioPluginManifest,
	defaultStudioPluginOutputPath,
	generateManifestModule,
	generateStudioPlugin,
	generateStudioPluginRbxm,
	generateStudioPluginRbxmx,
	luaLongString,
	resolveManifestOutputPath,
	resolveStudioPluginOutputPath,
	robloxStudioPluginsDir,
} = require("../src/studio-plugin");

// --- Config parsing ---
console.log("Testing config parsing...");

const toml = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/image-assets.ts"

[[sync]]
name = "meshes"
path = "assets/meshes"
output = "src/shared/mesh-assets.ts"
assetType = "Model"
`;

const config = parseConfig(toml);
assert.deepStrictEqual(config.creator, { type: "user", id: 12345 });
assert.strictEqual(config.sync.length, 2);
assert.strictEqual(config.sync[0].name, "images");
assert.strictEqual(config.sync[0].path, "assets/images");
assert.strictEqual(config.sync[1].assetType, "Model");
console.log("  config parsing OK");

// --- Config with comments ---
console.log("Testing config with comments...");

const toml2 = `
[creator]
type = "group"
id = 99999 # my group

[[sync]]
name = "sounds"
path = "assets/sounds"
output = "src/shared/sound-assets.ts"
`;

const config2 = parseConfig(toml2);
assert.strictEqual(config2.creator.type, "group");
assert.strictEqual(config2.creator.id, 99999);
console.log("  config with comments OK");

// --- Tree building (with extensions in keys) ---
console.log("Testing tree building...");

const lock = {
	"ui/button.png": { assetId: "111" },
	"ui/icon.png": { assetId: "222" },
	"fx/spark.png": { assetId: "333" },
	"logo.png": { assetId: "444" },
};

const tree = buildTree(lock);
assert.strictEqual(tree.ui["button.png"], "rbxassetid://111");
assert.strictEqual(tree.ui["icon.png"], "rbxassetid://222");
assert.strictEqual(tree.fx["spark.png"], "rbxassetid://333");
assert.strictEqual(tree["logo.png"], "rbxassetid://444");
console.log("  tree building OK");

// --- Luau generation ---
console.log("Testing Luau generation...");

const luau = generateLuau(lock, "images");
assert(luau.includes("local images ="));
assert(luau.includes("return images"));
assert(luau.includes('["button.png"] = "rbxassetid://111"'));
assert(luau.includes('["spark.png"] = "rbxassetid://333"'));
assert(luau.includes("auto-generated by rocas"));
console.log("  Luau generation OK");

// --- d.ts generation ---
console.log("Testing d.ts generation...");

const dts = generateDts(lock, "images");
assert(dts.includes("declare const images:"));
assert(dts.includes("export = images"));
assert(dts.includes('"button.png": string'));
assert(dts.includes('"icon.png": string'));
assert(dts.includes("auto-generated by rocas"));
console.log("  d.ts generation OK");

// --- Flat keys ---
console.log("Testing flat keys (no nesting)...");

const flatLock = {
	"walk.rbxm": { assetId: "555" },
	"run.rbxm": { assetId: "666" },
};

const flatLuau = generateLuau(flatLock, "animations");
assert(flatLuau.includes('["walk.rbxm"] = "rbxassetid://555"'));
assert(flatLuau.includes('["run.rbxm"] = "rbxassetid://666"'));

const flatDts = generateDts(flatLock, "animations");
assert(flatDts.includes('"walk.rbxm": string'));
assert(flatDts.includes('"run.rbxm": string'));
console.log("  flat keys OK");

// --- stripExtensions ---
console.log("Testing stripExtensions...");

const treeStripped = buildTree(lock, { stripExtensions: true });
assert.strictEqual(treeStripped.ui.button, "rbxassetid://111");
assert.strictEqual(treeStripped.ui.icon, "rbxassetid://222");
assert.strictEqual(treeStripped.fx.spark, "rbxassetid://333");
assert.strictEqual(treeStripped.logo, "rbxassetid://444");
console.log("  stripExtensions OK");

// --- Luau strict mode generation ---
console.log("Testing Luau strict mode generation...");

const luauStrict = generateLuau(lock, "images", { strict: true, stripExtensions: true });
assert(luauStrict.includes("--!strict"));
assert(luauStrict.includes("type ImagesType = {"));
assert(luauStrict.includes("local images: ImagesType = {"));
assert(luauStrict.includes("return images"));
assert(luauStrict.includes("\tbutton: string,"));
assert(luauStrict.includes('\tbutton = "rbxassetid://111"'));
assert(!luauStrict.includes(".png"));
console.log("  Luau strict mode OK");

// --- Luau generation with stripExtensions (non-strict) ---
console.log("Testing Luau generation with stripExtensions...");

const luauStripOnly = generateLuau(lock, "images", { stripExtensions: true });
assert(!luauStripOnly.includes("--!strict"));
assert(luauStripOnly.includes('button = "rbxassetid://111"'));
assert(!luauStripOnly.includes(".png"));
console.log("  Luau stripExtensions (non-strict) OK");

// --- d.ts generation with stripExtensions ---
console.log("Testing d.ts generation with stripExtensions...");

const dtsStripped = generateDts(lock, "images", { stripExtensions: true });
assert(dtsStripped.includes("button: string"));
assert(dtsStripped.includes("spark: string"));
assert(!dtsStripped.includes(".png"));
console.log("  d.ts stripExtensions OK");

// --- Config with format and stripExtensions ---
console.log("Testing config with format and stripExtensions...");

const toml3 = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/images"
format = "luau"
stripExtensions = true
`;

const config3 = parseConfig(toml3);
assert.strictEqual(config3.sync[0].format, "luau");
assert.strictEqual(config3.sync[0].stripExtensions, true);
console.log("  config format/stripExtensions OK");

// --- Codegen format registry ---
console.log("Testing codegen format registry...");

assert.strictEqual(DEFAULT_CODEGEN_FORMAT, "luau");
assert.deepStrictEqual(listCodegenFormats(), ["luau", "roblox-ts"]);
assert.strictEqual(resolveCodegenFormat().name, "luau");
assert.strictEqual(resolveCodegenFormat("roblox-ts").name, "roblox-ts");
assert.throws(() => resolveCodegenFormat("unknown"), /Unsupported sync format: unknown/);
assert.throws(() => registerCodegenFormat({ name: "broken" }), /name and render function/);
console.log("  codegen format registry OK");

// --- Extension mapping ---
console.log("Testing extension mapping...");

assert.strictEqual(EXT_TO_ASSET_TYPE[".png"], "Decal");
assert.strictEqual(EXT_TO_ASSET_TYPE[".wav"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".flac"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".fbx"], "Model");
assert.strictEqual(EXT_TO_ASSET_TYPE[".rbxm"], "Animation");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mp4"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mov"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".xyz"], undefined);
console.log("  extension mapping OK");

// --- Config fingerprint ---
console.log("Testing config fingerprint...");

const fpUser = configFingerprint({ type: "user", id: 12345 }, "Model");
assert.strictEqual(configFingerprint({ type: "user", id: 12345 }, "Model"), fpUser, "same inputs → same fingerprint");
assert.strictEqual(configFingerprint({ type: "user", id: "12345" }, "Model"), fpUser, "id type-coerced (number vs string)");
assert.notStrictEqual(configFingerprint({ type: "user", id: 99999 }, "Model"), fpUser, "different creator id → different");
assert.notStrictEqual(configFingerprint({ type: "group", id: 12345 }, "Model"), fpUser, "user vs group → different");
assert.notStrictEqual(configFingerprint({ type: "user", id: 12345 }, "Decal"), fpUser, "different assetType → different");
console.log("  config fingerprint OK");

// --- Sync action planning ---
console.log("Testing sync action planning...");

assert.strictEqual(planSyncAction(undefined, "h1", "fp1"), "upload", "no cache → upload");
assert.strictEqual(planSyncAction({ hash: "h0", config: "fp1" }, "h1", "fp1"), "upload", "content changed → upload");
assert.strictEqual(planSyncAction({ hash: "h1", config: "fp1" }, "h1", "fp1"), "reuse", "all matching → reuse");
assert.strictEqual(planSyncAction({ hash: "h1" }, "h1", "fp1"), "rebaseline", "legacy entry (no config) → rebaseline");
assert.strictEqual(planSyncAction({ hash: "h1", config: "fp0" }, "h1", "fp1"), "upload", "config changed → upload");
console.log("  sync action planning OK");

// --- Upload content type mapping ---
console.log("Testing upload content type mapping...");

assert.strictEqual(contentTypeFor("texture.png"), "image/png");
assert.strictEqual(contentTypeFor("mesh.fbx"), "model/fbx");
assert.strictEqual(contentTypeFor("scene.glb"), "model/gltf-binary");
assert.strictEqual(contentTypeFor("unknown.bin"), "application/octet-stream");
console.log("  upload content type mapping OK");

// --- Asset map from lock files ---
console.log("Testing asset map generation...");

const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-test-"));
const textureDir = path.join(tempDir, "assets", "textures");
fs.mkdirSync(path.join(textureDir, "Texture"), { recursive: true });
fs.writeFileSync(path.join(textureDir, "Texture", "Particle01.png"), Buffer.from([1, 2, 3]));
fs.writeFileSync(path.join(textureDir, "Texture", "Particle02.png"), Buffer.from([4, 5, 6, 7]));
fs.writeFileSync(
	path.join(textureDir, "images.lock.json"),
	JSON.stringify(
		{
			"Texture/Particle01.png": { assetId: "777", hash: "abc" },
			"Texture/Particle02.png": { assetId: "rbxassetid://888", hash: "def" },
		},
		null,
		2,
	),
);

const mapConfig = {
	creator: { type: "user", id: 12345 },
	sync: [{ name: "images", path: "assets/textures", output: "src/images" }],
};
const assetMap = buildAssetMap(mapConfig, tempDir);
const particlePath = path.resolve(textureDir, "Texture", "Particle01.png").replace(/\\/g, "/");
assert.strictEqual(lockPathForSync(mapConfig.sync[0], tempDir), path.join(textureDir, "images.lock.json"));
assert.strictEqual(assetMap.bySourcePath[particlePath], "rbxassetid://777");
assert.strictEqual(assetMap.byRelativePath["Texture/Particle02.png"], "rbxassetid://888");
assert.strictEqual(assetMap.groups.images["Texture/Particle01.png"], "rbxassetid://777");
console.log("  asset map generation OK");

// --- Studio plugin generation ---
console.log("Testing Studio plugin generation...");

const studioManifest = buildStudioPluginManifest(mapConfig, tempDir);
assert.strictEqual(studioManifest.generatedBy, "rocas");
assert.strictEqual(studioManifest.assets.length, 2);
assert.strictEqual(studioManifest.assets[0].group, "images");
assert.strictEqual(studioManifest.assets[0].assetType, "Decal");
assert.strictEqual(studioManifest.assets[0].assetId, "rbxassetid://777");
assert.strictEqual(studioManifest.assets[0].sourcePath, "assets/textures/Texture/Particle01.png");
assert.strictEqual(studioManifest.assets[0].source, "uploaded");

const pluginSource = generateStudioPlugin(studioManifest);
assert(!pluginSource.includes("\0"));
assert(pluginSource.includes("plugin:CreateToolbar(\"rocas\")"));
assert(pluginSource.includes("InsertService:LoadAsset"));
assert(pluginSource.includes("GetPropertyChangedSignal(\"Source\")"));
assert(pluginSource.includes("game.DescendantAdded:Connect(watchScript)"));
assert(pluginSource.includes("string.char(0)"));
assert(pluginSource.includes("ROCAS_MANIFEST_JSON_BEGIN"));
assert(pluginSource.includes("ReplicatedStorage:GetDescendants()"));
assert(!pluginSource.includes("Texture/Particle01.png"));
assert(!pluginSource.includes("rbxassetid://888"));

const pluginModel = generateStudioPluginRbxmx(pluginSource);
assert(pluginModel.includes('<Item class="Script"'));
assert(pluginModel.includes('<ProtectedString name="Source"><![CDATA['));
assert(pluginModel.includes("plugin:CreateToolbar(\"rocas\")"));

const pluginBinaryModel = generateStudioPluginRbxm(pluginSource);
const parsedPluginModel = RobloxFile.ReadFromBuffer(pluginBinaryModel);
assert(parsedPluginModel);
assert.strictEqual(parsedPluginModel.Roots.length, 1);
assert.strictEqual(parsedPluginModel.Roots[0].ClassName, "Script");
assert.strictEqual(parsedPluginModel.Roots[0].Name, "rocas");
assert(!parsedPluginModel.Roots[0].Source.includes("\0"));
assert(parsedPluginModel.Roots[0].Source.includes("plugin:CreateToolbar(\"rocas\")"));

const manifestModule = generateManifestModule(studioManifest);
assert(manifestModule.includes("ROCAS_MANIFEST_JSON_BEGIN"));
assert(manifestModule.includes("ROCAS_MANIFEST_JSON_END"));
assert(manifestModule.includes("Texture/Particle01.png"));
assert(manifestModule.includes("rbxassetid://888"));

const localStudioManifest = buildStudioPluginManifest(mapConfig, tempDir, { local: true });
assert.strictEqual(localStudioManifest.mode, "local");
assert.strictEqual(localStudioManifest.assets.length, 2);
assert.strictEqual(localStudioManifest.assets[0].source, "local");
assert.strictEqual(localStudioManifest.assets[0].assetId, undefined);
assert.strictEqual(localStudioManifest.assets[0].size, 3);
assert.strictEqual(localStudioManifest.assets[0].sourcePath, "assets/textures/Texture/Particle01.png");

const localManifestModule = generateManifestModule(localStudioManifest);
assert(localManifestModule.includes("PromptImportFilesAsync") === false);
assert(localManifestModule.includes('"mode": "local"'));
assert(pluginSource.includes("PromptImportFilesAsync"));
assert(pluginSource.includes("PromptImportFileAsync"));
assert(pluginSource.includes("GetTemporaryId"));
assert.strictEqual(luaLongString("plain"), "[[plain]]");
assert.strictEqual(luaLongString("has ]] marker"), "[=[has ]] marker]=]");
assert.strictEqual(resolveManifestOutputPath(tempDir), path.join(tempDir, "src", "shared", "RocasManifest.luau"));
assert.strictEqual(
	robloxStudioPluginsDir({ LOCALAPPDATA: "C:\\Users\\Example\\AppData\\Local" }, "win32"),
	path.join("C:\\Users\\Example\\AppData\\Local", "Roblox", "Plugins"),
);
assert.strictEqual(
	defaultStudioPluginOutputPath(tempDir, { LOCALAPPDATA: "C:\\Users\\Example\\AppData\\Local" }, "win32"),
	path.join("C:\\Users\\Example\\AppData\\Local", "Roblox", "Plugins", "rocas-studio-plugin.rbxm"),
);
assert.strictEqual(resolveStudioPluginOutputPath(tempDir, "custom/plugin.luau"), path.resolve(tempDir, "custom/plugin.luau"));
console.log("  Studio plugin generation OK");

(async () => {
	// --- syncOne codegen defaults ---
	console.log("Testing syncOne codegen defaults...");

	const codegenDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-codegen-test-"));
	const imageDir = path.join(codegenDir, "assets", "images");
	fs.mkdirSync(imageDir, { recursive: true });
	fs.writeFileSync(
		path.join(imageDir, "images.lock.json"),
		JSON.stringify({ "ui/button.png": { assetId: "111", hash: "abc" } }, null, 2),
	);

	await syncOne(
		{
			name: "images",
			path: "assets/images",
			output: "src/shared/images",
			stripExtensions: true,
		},
		{ type: "user", id: 12345 },
		"unused-api-key",
		codegenDir,
	);

	const defaultLuauPath = path.join(codegenDir, "src", "shared", "images.luau");
	const defaultDtsPath = path.join(codegenDir, "src", "shared", "images.d.ts");
	const defaultLuau = fs.readFileSync(defaultLuauPath, "utf8");
	assert(defaultLuau.includes("--!strict"));
	assert(defaultLuau.includes("type ImagesType = {"));
	assert(defaultLuau.includes("button: string"));
	assert(!fs.existsSync(defaultDtsPath));

	await syncOne(
		{
			name: "images",
			path: "assets/images",
			output: "src/shared/rbxts-images",
			format: "roblox-ts",
		},
		{ type: "user", id: 12345 },
		"unused-api-key",
		codegenDir,
	);

	const robloxTsLuauPath = path.join(codegenDir, "src", "shared", "rbxts-images.luau");
	const robloxTsDtsPath = path.join(codegenDir, "src", "shared", "rbxts-images.d.ts");
	assert(fs.existsSync(robloxTsLuauPath));
	assert(fs.existsSync(robloxTsDtsPath));
	assert(!fs.readFileSync(robloxTsLuauPath, "utf8").includes("--!strict"));
	assert(fs.readFileSync(robloxTsDtsPath, "utf8").includes("declare const images:"));

	await assert.rejects(
		() =>
			syncOne(
				{
					name: "images",
					path: "assets/images",
					output: "src/shared/unknown",
					format: "unknown",
				},
				{ type: "user", id: 12345 },
				"unused-api-key",
				codegenDir,
			),
		/Unsupported sync format: unknown/,
	);

	console.log("  syncOne codegen defaults OK");

	// --- syncOne config-aware change detection (offline; no upload) ---
	console.log("Testing syncOne config-aware change detection...");

	const fpDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-fp-test-"));
	const fpAssetDir = path.join(fpDir, "assets", "images");
	fs.mkdirSync(path.join(fpAssetDir, "ui"), { recursive: true });
	const fpFile = path.join(fpAssetDir, "ui", "button.png");
	fs.writeFileSync(fpFile, "button-bytes");
	const fpHash = fileHash(fpFile);
	const fpLockPath = path.join(fpAssetDir, "images.lock.json");
	const fpCreator = { type: "user", id: 12345 };
	const fpSync = { name: "images", path: "assets/images" };
	const expectedFp = configFingerprint(fpCreator, "Decal");

	// (1) reuse: hash と config が一致 → アップロードせずスキップ、ロックは据え置き
	fs.writeFileSync(
		fpLockPath,
		JSON.stringify({ "ui/button.png": { assetId: "111", hash: fpHash, config: expectedFp } }, null, 2),
	);
	await syncOne(fpSync, fpCreator, "unused-api-key", fpDir);
	let fpLock = JSON.parse(fs.readFileSync(fpLockPath, "utf8"));
	assert.strictEqual(fpLock["ui/button.png"].assetId, "111", "reuse keeps assetId");
	assert.strictEqual(fpLock["ui/button.png"].config, expectedFp, "reuse keeps config");

	// (2) rebaseline: 旧ロック (config 無し) → 再アップロードせず config を記録する
	fs.writeFileSync(fpLockPath, JSON.stringify({ "ui/button.png": { assetId: "111", hash: fpHash } }, null, 2));
	await syncOne(fpSync, fpCreator, "unused-api-key", fpDir);
	fpLock = JSON.parse(fs.readFileSync(fpLockPath, "utf8"));
	assert.strictEqual(fpLock["ui/button.png"].assetId, "111", "rebaseline keeps assetId (no re-upload)");
	assert.strictEqual(fpLock["ui/button.png"].config, expectedFp, "rebaseline records config baseline");
	// 設定 (creator) が変わった場合に再アップロードされる判断は planSyncAction の単体テストで担保
	// (実アップロードは Open Cloud への通信が必要なためここでは実行しない)。
	assert.strictEqual(
		planSyncAction(fpLock["ui/button.png"], fpHash, configFingerprint({ type: "user", id: 99999 }, "Decal")),
		"upload",
		"creator change after rebaseline → upload",
	);
	console.log("  syncOne config-aware change detection OK");

	console.log("\nAll tests passed!");
})().catch((error) => {
	console.error(error);
	process.exit(1);
});
