const assert = require("assert");
const { execFileSync } = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { RobloxFile } = require("rbxm-parser");
const { parseConfig } = require("../src/config");
const { generateLuau, generateDts, buildTree, renderLuauType } = require("../src/codegen");
const { DEFAULT_CODEGEN_FORMAT, listCodegenFormats, registerCodegenFormat, resolveCodegenFormat } = require("../src/formats");
const {
	EXT_TO_ASSET_TYPE,
	CONVERTED_EXT_TO_ASSET_TYPE,
	syncOne,
	configFingerprint,
	planSyncAction,
	resolveAssetType,
	fileHash,
	needsImageId,
} = require("../src/sync");
const { contentTypeFor } = require("../src/upload");
const {
	fetchAssetContent,
	fetchDecalImageId,
	extractImageIdFromAssetBody,
	parseAssetLocation,
	assetDeliveryEndpoints,
} = require("../src/image-id");
const { fetchAll, detectContentExtension, planFetchAction, resolveFetchDir, DEFAULT_FETCH_DIR } = require("../src/fetch");
const { buildAssetMap, lockPathForSync, resolveEntryAssetId } = require("../src/asset-map");
const {
	buildStudioPluginManifest,
	defaultStudioPluginOutputPath,
	generateManifestModule,
	generateStudioPlugin,
	generateStudioPluginRbxm,
	generateStudioPluginRbxmx,
	luaLongString,
	resolveManifestOutputPath,
	resolveStudioPluginOutputPath,
	robloxStudioPluginsDir,
} = require("../src/studio-plugin");

// --- Config parsing ---
console.log("Testing config parsing...");

const toml = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/image-assets.ts"

[[sync]]
name = "meshes"
path = "assets/meshes"
output = "src/shared/mesh-assets.ts"
assetType = "Model"
`;

const config = parseConfig(toml);
assert.deepStrictEqual(config.creator, { type: "user", id: 12345 });
assert.strictEqual(config.sync.length, 2);
assert.strictEqual(config.sync[0].name, "images");
assert.strictEqual(config.sync[0].path, "assets/images");
assert.strictEqual(config.sync[1].assetType, "Model");
console.log("  config parsing OK");

// --- Config with comments ---
console.log("Testing config with comments...");

const toml2 = `
[creator]
type = "group"
id = 99999 # my group

[[sync]]
name = "sounds"
path = "assets/sounds"
output = "src/shared/sound-assets.ts"
`;

const config2 = parseConfig(toml2);
assert.strictEqual(config2.creator.type, "group");
assert.strictEqual(config2.creator.id, 99999);
console.log("  config with comments OK");

// --- Tree building (with extensions in keys) ---
console.log("Testing tree building...");

const lock = {
	"ui/button.png": { assetId: "111" },
	"ui/icon.png": { assetId: "222" },
	"fx/spark.png": { assetId: "333" },
	"logo.png": { assetId: "444" },
};

const tree = buildTree(lock);
assert.strictEqual(tree.ui["button.png"], "rbxassetid://111");
assert.strictEqual(tree.ui["icon.png"], "rbxassetid://222");
assert.strictEqual(tree.fx["spark.png"], "rbxassetid://333");
assert.strictEqual(tree["logo.png"], "rbxassetid://444");
console.log("  tree building OK");

// --- Luau generation ---
console.log("Testing Luau generation...");

const luau = generateLuau(lock, "images");
assert(luau.includes("local images ="));
assert(luau.includes("return images"));
assert(luau.includes('["button.png"] = "rbxassetid://111"'));
assert(luau.includes('["spark.png"] = "rbxassetid://333"'));
assert(luau.includes("auto-generated by rocas"));
console.log("  Luau generation OK");

// --- d.ts generation ---
console.log("Testing d.ts generation...");

const dts = generateDts(lock, "images");
assert(dts.includes("declare const images:"));
assert(dts.includes("export = images"));
assert(dts.includes('"button.png": string'));
assert(dts.includes('"icon.png": string'));
assert(dts.includes("auto-generated by rocas"));
console.log("  d.ts generation OK");

// --- Flat keys ---
console.log("Testing flat keys (no nesting)...");

const flatLock = {
	"walk.rbxm": { assetId: "555" },
	"run.rbxm": { assetId: "666" },
};

const flatLuau = generateLuau(flatLock, "animations");
assert(flatLuau.includes('["walk.rbxm"] = "rbxassetid://555"'));
assert(flatLuau.includes('["run.rbxm"] = "rbxassetid://666"'));

const flatDts = generateDts(flatLock, "animations");
assert(flatDts.includes('"walk.rbxm": string'));
assert(flatDts.includes('"run.rbxm": string'));
console.log("  flat keys OK");

// --- stripExtensions ---
console.log("Testing stripExtensions...");

const treeStripped = buildTree(lock, { stripExtensions: true });
assert.strictEqual(treeStripped.ui.button, "rbxassetid://111");
assert.strictEqual(treeStripped.ui.icon, "rbxassetid://222");
assert.strictEqual(treeStripped.fx.spark, "rbxassetid://333");
assert.strictEqual(treeStripped.logo, "rbxassetid://444");
console.log("  stripExtensions OK");

// --- Luau strict mode generation ---
console.log("Testing Luau strict mode generation...");

const luauStrict = generateLuau(lock, "images", { strict: true, stripExtensions: true });
assert(luauStrict.includes("--!strict"));
assert(luauStrict.includes("type ImagesType = {"));
assert(luauStrict.includes("local images: ImagesType = {"));
assert(luauStrict.includes("return images"));
assert(luauStrict.includes("\tbutton: string,"));
assert(luauStrict.includes('\tbutton = "rbxassetid://111"'));
assert(!luauStrict.includes(".png"));
console.log("  Luau strict mode OK");

// --- Luau generation with stripExtensions (non-strict) ---
console.log("Testing Luau generation with stripExtensions...");

const luauStripOnly = generateLuau(lock, "images", { stripExtensions: true });
assert(!luauStripOnly.includes("--!strict"));
assert(luauStripOnly.includes('button = "rbxassetid://111"'));
assert(!luauStripOnly.includes(".png"));
console.log("  Luau stripExtensions (non-strict) OK");

// --- d.ts generation with stripExtensions ---
console.log("Testing d.ts generation with stripExtensions...");

const dtsStripped = generateDts(lock, "images", { stripExtensions: true });
assert(dtsStripped.includes("button: string"));
assert(dtsStripped.includes("spark: string"));
assert(!dtsStripped.includes(".png"));
console.log("  d.ts stripExtensions OK");

// --- Config with format and stripExtensions ---
console.log("Testing config with format and stripExtensions...");

const toml3 = `
[creator]
type = "user"
id = 12345

[[sync]]
name = "images"
path = "assets/images"
output = "src/shared/images"
format = "luau"
stripExtensions = true
`;

const config3 = parseConfig(toml3);
assert.strictEqual(config3.sync[0].format, "luau");
assert.strictEqual(config3.sync[0].stripExtensions, true);
console.log("  config format/stripExtensions OK");

// --- Codegen format registry ---
console.log("Testing codegen format registry...");

assert.strictEqual(DEFAULT_CODEGEN_FORMAT, "luau");
assert.deepStrictEqual(listCodegenFormats(), ["luau", "roblox-ts"]);
assert.strictEqual(resolveCodegenFormat().name, "luau");
assert.strictEqual(resolveCodegenFormat("roblox-ts").name, "roblox-ts");
assert.throws(() => resolveCodegenFormat("unknown"), /Unsupported sync format: unknown/);
assert.throws(() => registerCodegenFormat({ name: "broken" }), /name and render function/);
console.log("  codegen format registry OK");

// --- Extension mapping ---
console.log("Testing extension mapping...");

assert.strictEqual(EXT_TO_ASSET_TYPE[".png"], "Decal");
assert.strictEqual(EXT_TO_ASSET_TYPE[".wav"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".flac"], "Audio");
assert.strictEqual(EXT_TO_ASSET_TYPE[".rbxm"], "Model");
assert.strictEqual(EXT_TO_ASSET_TYPE[".rbxmx"], "Model");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mp4"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".mov"], "Video");
assert.strictEqual(EXT_TO_ASSET_TYPE[".xyz"], undefined);

// アップロード時に変換される形式は自動判定から外れている (assetType の明示が要る)
for (const ext of [".fbx", ".glb", ".gltf", ".obj"]) {
	assert.strictEqual(EXT_TO_ASSET_TYPE[ext], undefined, `${ext} is not auto-detected`);
	assert.strictEqual(CONVERTED_EXT_TO_ASSET_TYPE[ext], "Model", `${ext} is known as a converted format`);
}
console.log("  extension mapping OK");

// --- Asset type resolution ---
console.log("Testing asset type resolution...");

// 変換される形式は明示的な許可が要る。assetType は「どの型で上げるか」の指定であって
// 許可ではないので、それだけでは通らない。
assert.deepStrictEqual(resolveAssetType({}, ".fbx"), { skip: "converted", assetType: "Model" });
assert.deepStrictEqual(resolveAssetType({ assetType: "Model" }, ".fbx"), { skip: "converted", assetType: "Model" });
assert.deepStrictEqual(resolveAssetType({ allowConvertedFormats: false }, ".obj"), {
	skip: "converted",
	assetType: "Model",
});
assert.deepStrictEqual(resolveAssetType({ allowConvertedFormats: true }, ".fbx"), { assetType: "Model" });
// 許可さえあれば assetType は要らない (変換後の型が入る)
assert.deepStrictEqual(resolveAssetType({ allowConvertedFormats: true }, ".gltf"), { assetType: "Model" });
assert.deepStrictEqual(resolveAssetType({ allowConvertedFormats: true, assetType: "Animation" }, ".fbx"), {
	assetType: "Animation",
});

// 変換されない形式は従来どおり
assert.deepStrictEqual(resolveAssetType({}, ".png"), { assetType: "Decal" });
assert.deepStrictEqual(resolveAssetType({}, ".rbxm"), { assetType: "Model" });
assert.deepStrictEqual(resolveAssetType({ assetType: "Animation" }, ".rbxm"), { assetType: "Animation" });
assert.deepStrictEqual(resolveAssetType({}, ".xyz"), { skip: "unsupported" });
assert.deepStrictEqual(resolveAssetType({ assetType: "Model" }, ".xyz"), { assetType: "Model" });
console.log("  asset type resolution OK");

// --- Config fingerprint ---
console.log("Testing config fingerprint...");

const fpUser = configFingerprint({ type: "user", id: 12345 }, "Model");
assert.strictEqual(configFingerprint({ type: "user", id: 12345 }, "Model"), fpUser, "same inputs → same fingerprint");
assert.strictEqual(configFingerprint({ type: "user", id: "12345" }, "Model"), fpUser, "id type-coerced (number vs string)");
assert.notStrictEqual(configFingerprint({ type: "user", id: 99999 }, "Model"), fpUser, "different creator id → different");
assert.notStrictEqual(configFingerprint({ type: "group", id: 12345 }, "Model"), fpUser, "user vs group → different");
assert.notStrictEqual(configFingerprint({ type: "user", id: 12345 }, "Decal"), fpUser, "different assetType → different");
console.log("  config fingerprint OK");

// --- Sync action planning ---
console.log("Testing sync action planning...");

assert.strictEqual(planSyncAction(undefined, "h1", "fp1"), "upload", "no cache → upload");
assert.strictEqual(planSyncAction({ hash: "h0", config: "fp1" }, "h1", "fp1"), "upload", "content changed, no assetType → upload");
assert.strictEqual(planSyncAction({ hash: "h1", config: "fp1" }, "h1", "fp1"), "reuse", "all matching → reuse");
assert.strictEqual(planSyncAction({ hash: "h1" }, "h1", "fp1"), "rebaseline", "legacy entry (no config) → rebaseline");
assert.strictEqual(planSyncAction({ hash: "h1", config: "fp0" }, "h1", "fp1"), "upload", "config changed → upload");

// 内容だけが変わったとき、Update Asset に対応する型だけ同じ assetId で上げ直す
const changedModel = { assetId: "123", hash: "h0", config: "fp1" };
assert.strictEqual(planSyncAction(changedModel, "h1", "fp1", "Model"), "update", "content changed, Model → update");
assert.strictEqual(
	planSyncAction(changedModel, "h1", "fp1", "Decal"),
	"upload",
	"content changed, type not updatable → upload",
);
assert.strictEqual(
	planSyncAction(changedModel, "h1", "fp1", "Animation"),
	"upload",
	"content changed, Animation is not documented as updatable → upload",
);
assert.strictEqual(
	planSyncAction(changedModel, "h1", "fp2", "Model"),
	"upload",
	"content and config both changed → upload (new asset)",
);
assert.strictEqual(
	planSyncAction({ hash: "h0", config: "fp1" }, "h1", "fp1", "Model"),
	"upload",
	"content changed but no assetId to update → upload",
);
assert.strictEqual(
	planSyncAction({ assetId: "", hash: "h0", config: "fp1" }, "h1", "fp1", "Model"),
	"upload",
	"content changed but assetId is blank → upload",
);
assert.strictEqual(
	planSyncAction({ assetId: "123", hash: "h0" }, "h1", "fp1", "Model"),
	"upload",
	"legacy entry (no config) with changed content → upload",
);
assert.strictEqual(
	planSyncAction({ assetId: "123", hash: "h1", config: "fp1" }, "h1", "fp1", "Model"),
	"reuse",
	"Model with unchanged content → reuse",
);
console.log("  sync action planning OK");

// --- Upload content type mapping ---
console.log("Testing upload content type mapping...");

assert.strictEqual(contentTypeFor("texture.png"), "image/png");
assert.strictEqual(contentTypeFor("mesh.fbx"), "model/fbx");
assert.strictEqual(contentTypeFor("scene.glb"), "model/gltf-binary");
assert.strictEqual(contentTypeFor("map.rbxm"), "model/x-rbxm");
assert.strictEqual(contentTypeFor("map.rbxmx"), "model/x-rbxm");
assert.strictEqual(contentTypeFor("MAP.RBXM"), "model/x-rbxm", "extension matching is case-insensitive");
assert.strictEqual(contentTypeFor("unknown.bin"), "application/octet-stream");
console.log("  upload content type mapping OK");

// --- Decal image id extraction ---
console.log("Testing decal image id extraction...");

const decalXml =
	'<roblox version="4">\n' +
	'\t<Item class="Decal" referent="RBX0">\n' +
	"\t\t<Properties>\n" +
	'\t\t\t<string name="Name">button</string>\n' +
	'\t\t\t<Content name="Other"><url>rbxassetid://111</url></Content>\n' +
	'\t\t\t<Content name="Texture"><url>http://www.roblox.com/asset/?id=555</url></Content>\n' +
	"\t\t</Properties>\n" +
	"\t</Item>\n" +
	"</roblox>\n";

assert.strictEqual(extractImageIdFromAssetBody(decalXml), "555", "Texture property wins over other urls");
assert.strictEqual(extractImageIdFromAssetBody(Buffer.from(decalXml)), "555", "works on a Buffer");
assert.strictEqual(
	extractImageIdFromAssetBody(Buffer.from("<roblox!\x89\xff\r\n\x1a\n\x00INSTrbxassetid://777\x00", "latin1")),
	"777",
	"binary rbxm body still yields the url",
);
assert.strictEqual(extractImageIdFromAssetBody("no ids here"), null);
assert.strictEqual(extractImageIdFromAssetBody(null), null);
assert.strictEqual(
	parseAssetLocation(JSON.stringify({ location: "https://c0.rbxcdn.com/abc" })),
	"https://c0.rbxcdn.com/abc",
	"single-location shape (assetdelivery v1/assetId)",
);
assert.strictEqual(
	parseAssetLocation(JSON.stringify({ locations: [{ location: "https://c0.rbxcdn.com/def" }] })),
	"https://c0.rbxcdn.com/def",
	"multi-location shape (assetdelivery v2)",
);
assert.strictEqual(parseAssetLocation("not json"), null);
assert.strictEqual(parseAssetLocation(JSON.stringify({ locations: [] })), null);

// API キーがあれば Open Cloud 経由を先に試し、無ければ旧エンドポイントのみ
const keyedEndpoints = assetDeliveryEndpoints("123", "secret-key");
assert.strictEqual(keyedEndpoints.length, 2);
assert.strictEqual(keyedEndpoints[0].url, "https://apis.roblox.com/asset-delivery-api/v1/assetId/123");
assert.strictEqual(keyedEndpoints[0].headers["x-api-key"], "secret-key");
assert.strictEqual(keyedEndpoints[1].url, "https://assetdelivery.roblox.com/v1/assetId/123");
assert.deepStrictEqual(keyedEndpoints[1].headers, {}, "legacy endpoint is unauthenticated");
assert.strictEqual(assetDeliveryEndpoints("123", null).length, 1, "no api key = legacy only");

// 版を固定するときは .../assetId/{id}/version/{n}
const versionedEndpoints = assetDeliveryEndpoints("123", "secret-key", 3);
assert.strictEqual(versionedEndpoints[0].url, "https://apis.roblox.com/asset-delivery-api/v1/assetId/123/version/3");
assert.strictEqual(versionedEndpoints[1].url, "https://assetdelivery.roblox.com/v1/assetId/123/version/3");
console.log("  decal image id extraction OK");

// --- Fetched content extension detection ---
console.log("Testing fetched content extension detection...");

// 元ファイルの拡張子ではなく、返ってきた中身で決める (.fbx を上げると .rbxm が返る)
assert.strictEqual(detectContentExtension(Buffer.from("<roblox!\x89\xff\r\n\x1a\n", "latin1"), ".fbx"), ".rbxm");
assert.strictEqual(detectContentExtension(Buffer.from('<roblox version="4">', "latin1"), ".fbx"), ".rbxmx");
assert.strictEqual(detectContentExtension(Buffer.from("\x89PNG\r\n\x1a\n", "latin1"), ".jpg"), ".png");
assert.strictEqual(detectContentExtension(Buffer.from("\xff\xd8\xff\xe0", "latin1"), ".png"), ".jpg");
assert.strictEqual(detectContentExtension(Buffer.from("OggS\x00", "latin1"), ".mp3"), ".ogg");
assert.strictEqual(detectContentExtension(Buffer.from("\x00\x00\x00\x18ftypmp42", "latin1"), ".mov"), ".mp4");
// 判別できなければ lock のキーの拡張子、それも無ければ .bin
assert.strictEqual(detectContentExtension(Buffer.from("mystery bytes"), ".wav"), ".wav");
assert.strictEqual(detectContentExtension(Buffer.from("mystery bytes"), ""), ".bin");
assert.strictEqual(detectContentExtension("not a buffer", ".png"), ".png");
console.log("  fetched content extension detection OK");

// --- Fetch action planning ---
console.log("Testing fetch action planning...");

const fetched = { assetId: "222", hash: "h1", file: "222.png" };
assert.strictEqual(planFetchAction(fetched, "222", "h1", true), "reuse");
assert.strictEqual(planFetchAction(undefined, "222", "h1", true), "fetch", "never fetched");
assert.strictEqual(planFetchAction(fetched, "333", "h1", true), "fetch", "asset id changed");
assert.strictEqual(planFetchAction(fetched, "222", "h2", true), "fetch", "source hash changed");
assert.strictEqual(planFetchAction(fetched, "222", "h1", false), "fetch", "local file is gone");
assert.strictEqual(resolveFetchDir("/repo", undefined), path.resolve("/repo", DEFAULT_FETCH_DIR));
assert.strictEqual(resolveFetchDir("/repo", "somewhere"), path.resolve("/repo", "somewhere"));
console.log("  fetch action planning OK");

// --- Lock entry asset id resolution ---
console.log("Testing lock entry asset id resolution...");

assert.strictEqual(resolveEntryAssetId({ assetId: "111", imageId: "222" }), "222", "imageId wins");
assert.strictEqual(resolveEntryAssetId({ assetId: "111" }), "111", "falls back to assetId");
assert.strictEqual(resolveEntryAssetId({ assetId: "111", imageId: "" }), "111", "empty imageId ignored");
assert.strictEqual(resolveEntryAssetId({}), null);
assert.strictEqual(resolveEntryAssetId(undefined), null);

assert.strictEqual(needsImageId({ assetId: "111" }, "Decal"), true);
assert.strictEqual(needsImageId({ assetId: "111", imageId: "222" }, "Decal"), false, "already resolved");
assert.strictEqual(needsImageId({ assetId: "111" }, "Audio"), false, "only images carry a decal wrapper");
assert.strictEqual(needsImageId(undefined, "Decal"), false);

const imageIdLock = {
	"ui/button.png": { assetId: "111", imageId: "222" },
	"ui/icon.png": { assetId: "333" },
};
const imageIdTree = buildTree(imageIdLock);
assert.strictEqual(imageIdTree.ui["button.png"], "rbxassetid://222", "codegen emits the image id");
assert.strictEqual(imageIdTree.ui["icon.png"], "rbxassetid://333", "unresolved entries keep the decal id");
console.log("  lock entry asset id resolution OK");

// --- Asset map from lock files ---
console.log("Testing asset map generation...");

const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-test-"));
const textureDir = path.join(tempDir, "assets", "textures");
fs.mkdirSync(path.join(textureDir, "Texture"), { recursive: true });
fs.writeFileSync(path.join(textureDir, "Texture", "Particle01.png"), Buffer.from([1, 2, 3]));
fs.writeFileSync(path.join(textureDir, "Texture", "Particle02.png"), Buffer.from([4, 5, 6, 7]));
fs.writeFileSync(
	path.join(textureDir, "images.lock.json"),
	JSON.stringify(
		{
			"Texture/Particle01.png": { assetId: "777", hash: "abc" },
			"Texture/Particle02.png": { assetId: "rbxassetid://888", hash: "def" },
		},
		null,
		2,
	),
);

const mapConfig = {
	creator: { type: "user", id: 12345 },
	sync: [{ name: "images", path: "assets/textures", output: "src/images" }],
};
const assetMap = buildAssetMap(mapConfig, tempDir);
const particlePath = path.resolve(textureDir, "Texture", "Particle01.png").replace(/\\/g, "/");
assert.strictEqual(lockPathForSync(mapConfig.sync[0], tempDir), path.join(textureDir, "images.lock.json"));
assert.strictEqual(assetMap.bySourcePath[particlePath], "rbxassetid://777");
assert.strictEqual(assetMap.byRelativePath["Texture/Particle02.png"], "rbxassetid://888");
assert.strictEqual(assetMap.groups.images["Texture/Particle01.png"], "rbxassetid://777");
console.log("  asset map generation OK");

// --- Studio plugin generation ---
console.log("Testing Studio plugin generation...");

const studioManifest = buildStudioPluginManifest(mapConfig, tempDir);
assert.strictEqual(studioManifest.generatedBy, "rocas");
assert.strictEqual(studioManifest.assets.length, 2);
assert.strictEqual(studioManifest.assets[0].group, "images");
assert.strictEqual(studioManifest.assets[0].assetType, "Decal");
assert.strictEqual(studioManifest.assets[0].assetId, "rbxassetid://777");
assert.strictEqual(studioManifest.assets[0].sourcePath, "assets/textures/Texture/Particle01.png");
assert.strictEqual(studioManifest.assets[0].source, "uploaded");

const pluginSource = generateStudioPlugin(studioManifest);
assert(!pluginSource.includes("\0"));
assert(pluginSource.includes("plugin:CreateToolbar(\"rocas\")"));
assert(pluginSource.includes("InsertService:LoadAsset"));
assert(pluginSource.includes("GetPropertyChangedSignal(\"Source\")"));
assert(pluginSource.includes("game.DescendantAdded:Connect(watchScript)"));
assert(pluginSource.includes("string.char(0)"));
assert(pluginSource.includes("ROCAS_MANIFEST_JSON_BEGIN"));
assert(pluginSource.includes("ReplicatedStorage:GetDescendants()"));
assert(!pluginSource.includes("Texture/Particle01.png"));
assert(!pluginSource.includes("rbxassetid://888"));

const pluginModel = generateStudioPluginRbxmx(pluginSource);
assert(pluginModel.includes('<Item class="Script"'));
assert(pluginModel.includes('<ProtectedString name="Source"><![CDATA['));
assert(pluginModel.includes("plugin:CreateToolbar(\"rocas\")"));

const pluginBinaryModel = generateStudioPluginRbxm(pluginSource);
const parsedPluginModel = RobloxFile.ReadFromBuffer(pluginBinaryModel);
assert(parsedPluginModel);
assert.strictEqual(parsedPluginModel.Roots.length, 1);
assert.strictEqual(parsedPluginModel.Roots[0].ClassName, "Script");
assert.strictEqual(parsedPluginModel.Roots[0].Name, "rocas");
assert(!parsedPluginModel.Roots[0].Source.includes("\0"));
assert(parsedPluginModel.Roots[0].Source.includes("plugin:CreateToolbar(\"rocas\")"));

// rbxm-parser を読むのは .rbxm を書くときだけ。あれが要求するネイティブモジュール lz4 は
// npm 12 だとビルドされないことがあり、トップレベルで読むと lz4 を使わない sync / fetch /
// watch / help まで巻き添えで落ちる。別プロセスで確かめる — このテスト自身が先頭で
// rbxm-parser を読んでいるので、同じプロセスの require.cache では判定できない。
const probe = [
	`require(${JSON.stringify(path.resolve(__dirname, "../src/index.js"))});`,
	'const loaded = Object.keys(require.cache).some((key) => key.includes("rbxm-parser"));',
	'process.stdout.write(loaded ? "yes" : "no");',
].join("\n");
const loadedEagerly = execFileSync(process.execPath, ["-e", probe], { encoding: "utf8" });
assert.strictEqual(loadedEagerly, "no", "requiring the library must not load rbxm-parser (and its lz4 native module)");

const manifestModule = generateManifestModule(studioManifest);
assert(manifestModule.includes("ROCAS_MANIFEST_JSON_BEGIN"));
assert(manifestModule.includes("ROCAS_MANIFEST_JSON_END"));
assert(manifestModule.includes("Texture/Particle01.png"));
assert(manifestModule.includes("rbxassetid://888"));

const localStudioManifest = buildStudioPluginManifest(mapConfig, tempDir, { local: true });
assert.strictEqual(localStudioManifest.mode, "local");
assert.strictEqual(localStudioManifest.assets.length, 2);
assert.strictEqual(localStudioManifest.assets[0].source, "local");
assert.strictEqual(localStudioManifest.assets[0].assetId, undefined);
assert.strictEqual(localStudioManifest.assets[0].size, 3);
assert.strictEqual(localStudioManifest.assets[0].sourcePath, "assets/textures/Texture/Particle01.png");

const localManifestModule = generateManifestModule(localStudioManifest);
assert(localManifestModule.includes("PromptImportFilesAsync") === false);
assert(localManifestModule.includes('"mode": "local"'));
assert(pluginSource.includes("PromptImportFilesAsync"));
assert(pluginSource.includes("PromptImportFileAsync"));
assert(pluginSource.includes("GetTemporaryId"));
assert.strictEqual(luaLongString("plain"), "[[plain]]");
assert.strictEqual(luaLongString("has ]] marker"), "[=[has ]] marker]=]");
assert.strictEqual(resolveManifestOutputPath(tempDir), path.join(tempDir, "src", "shared", "RocasManifest.luau"));
assert.strictEqual(
	robloxStudioPluginsDir({ LOCALAPPDATA: "C:\\Users\\Example\\AppData\\Local" }, "win32"),
	path.join("C:\\Users\\Example\\AppData\\Local", "Roblox", "Plugins"),
);
assert.strictEqual(
	defaultStudioPluginOutputPath(tempDir, { LOCALAPPDATA: "C:\\Users\\Example\\AppData\\Local" }, "win32"),
	path.join("C:\\Users\\Example\\AppData\\Local", "Roblox", "Plugins", "rocas-studio-plugin.rbxm"),
);
assert.strictEqual(resolveStudioPluginOutputPath(tempDir, "custom/plugin.luau"), path.resolve(tempDir, "custom/plugin.luau"));
console.log("  Studio plugin generation OK");

// --- Asset map / manifest prefer the resolved image id ---
console.log("Testing image id propagation into asset map and manifest...");

const imageIdDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-imageid-test-"));
const imageIdAssetDir = path.join(imageIdDir, "assets", "images");
fs.mkdirSync(path.join(imageIdAssetDir, "ui"), { recursive: true });
fs.writeFileSync(path.join(imageIdAssetDir, "ui", "button.png"), Buffer.from([1, 2, 3]));
fs.writeFileSync(
	path.join(imageIdAssetDir, "images.lock.json"),
	JSON.stringify(
		{
			"ui/button.png": { assetId: "111", imageId: "222", hash: "abc" },
			"ui/legacy.png": { assetId: "333", hash: "def" },
		},
		null,
		2,
	),
);

const imageIdConfig = {
	creator: { type: "user", id: 12345 },
	sync: [{ name: "images", path: "assets/images" }],
};
const imageIdMap = buildAssetMap(imageIdConfig, imageIdDir);
assert.strictEqual(imageIdMap.groups.images["ui/button.png"], "rbxassetid://222", "asset map uses the image id");
assert.strictEqual(imageIdMap.groups.images["ui/legacy.png"], "rbxassetid://333", "unresolved falls back");

const imageIdManifest = buildStudioPluginManifest(imageIdConfig, imageIdDir);
assert.strictEqual(imageIdManifest.assets[0].path, "ui/button.png");
assert.strictEqual(imageIdManifest.assets[0].assetId, "rbxassetid://222", "manifest uses the image id");
assert.strictEqual(imageIdManifest.assets[1].assetId, "rbxassetid://333");
console.log("  image id propagation OK");

(async () => {
	// --- syncOne codegen defaults ---
	console.log("Testing syncOne codegen defaults...");

	const codegenDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-codegen-test-"));
	const imageDir = path.join(codegenDir, "assets", "images");
	fs.mkdirSync(imageDir, { recursive: true });
	fs.writeFileSync(
		path.join(imageDir, "images.lock.json"),
		JSON.stringify({ "ui/button.png": { assetId: "111", hash: "abc" } }, null, 2),
	);

	await syncOne(
		{
			name: "images",
			path: "assets/images",
			output: "src/shared/images",
			stripExtensions: true,
		},
		{ type: "user", id: 12345 },
		"unused-api-key",
		codegenDir,
	);

	const defaultLuauPath = path.join(codegenDir, "src", "shared", "images.luau");
	const defaultDtsPath = path.join(codegenDir, "src", "shared", "images.d.ts");
	const defaultLuau = fs.readFileSync(defaultLuauPath, "utf8");
	assert(defaultLuau.includes("--!strict"));
	assert(defaultLuau.includes("type ImagesType = {"));
	assert(defaultLuau.includes("button: string"));
	assert(!fs.existsSync(defaultDtsPath));

	await syncOne(
		{
			name: "images",
			path: "assets/images",
			output: "src/shared/rbxts-images",
			format: "roblox-ts",
		},
		{ type: "user", id: 12345 },
		"unused-api-key",
		codegenDir,
	);

	const robloxTsLuauPath = path.join(codegenDir, "src", "shared", "rbxts-images.luau");
	const robloxTsDtsPath = path.join(codegenDir, "src", "shared", "rbxts-images.d.ts");
	assert(fs.existsSync(robloxTsLuauPath));
	assert(fs.existsSync(robloxTsDtsPath));
	assert(!fs.readFileSync(robloxTsLuauPath, "utf8").includes("--!strict"));
	assert(fs.readFileSync(robloxTsDtsPath, "utf8").includes("declare const images:"));

	await assert.rejects(
		() =>
			syncOne(
				{
					name: "images",
					path: "assets/images",
					output: "src/shared/unknown",
					format: "unknown",
				},
				{ type: "user", id: 12345 },
				"unused-api-key",
				codegenDir,
			),
		/Unsupported sync format: unknown/,
	);

	console.log("  syncOne codegen defaults OK");

	// --- syncOne config-aware change detection (offline; no upload) ---
	console.log("Testing syncOne config-aware change detection...");

	const fpDir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-fp-test-"));
	const fpAssetDir = path.join(fpDir, "assets", "images");
	fs.mkdirSync(path.join(fpAssetDir, "ui"), { recursive: true });
	const fpFile = path.join(fpAssetDir, "ui", "button.png");
	fs.writeFileSync(fpFile, "button-bytes");
	const fpHash = fileHash(fpFile);
	const fpLockPath = path.join(fpAssetDir, "images.lock.json");
	const fpCreator = { type: "user", id: 12345 };
	const fpSync = { name: "images", path: "assets/images" };
	const expectedFp = configFingerprint(fpCreator, "Decal");

	// Image ID の解決はネットワークを叩くので、オフラインテストでは差し替える
	const stubImageId = { resolveImageId: async (decalId) => `${decalId}0` };

	// (1) reuse: hash と config が一致 → アップロードせずスキップ、ロックは据え置き
	fs.writeFileSync(
		fpLockPath,
		JSON.stringify(
			{ "ui/button.png": { assetId: "111", imageId: "999", hash: fpHash, config: expectedFp } },
			null,
			2,
		),
	);
	await syncOne(fpSync, fpCreator, "unused-api-key", fpDir, stubImageId);
	let fpLock = JSON.parse(fs.readFileSync(fpLockPath, "utf8"));
	assert.strictEqual(fpLock["ui/button.png"].assetId, "111", "reuse keeps assetId");
	assert.strictEqual(fpLock["ui/button.png"].config, expectedFp, "reuse keeps config");
	assert.strictEqual(fpLock["ui/button.png"].imageId, "999", "reuse keeps an already-resolved imageId");

	// (2) rebaseline: 旧ロック (config 無し) → 再アップロードせず config を記録する
	fs.writeFileSync(fpLockPath, JSON.stringify({ "ui/button.png": { assetId: "111", hash: fpHash } }, null, 2));
	await syncOne(fpSync, fpCreator, "unused-api-key", fpDir, stubImageId);
	fpLock = JSON.parse(fs.readFileSync(fpLockPath, "utf8"));
	assert.strictEqual(fpLock["ui/button.png"].assetId, "111", "rebaseline keeps assetId (no re-upload)");
	assert.strictEqual(fpLock["ui/button.png"].config, expectedFp, "rebaseline records config baseline");
	assert.strictEqual(fpLock["ui/button.png"].imageId, "1110", "rebaseline backfills the image id");
	// 設定 (creator) が変わった場合に再アップロードされる判断は planSyncAction の単体テストで担保
	// (実アップロードは Open Cloud への通信が必要なためここでは実行しない)。
	assert.strictEqual(
		planSyncAction(fpLock["ui/button.png"], fpHash, configFingerprint({ type: "user", id: 99999 }, "Decal")),
		"upload",
		"creator change after rebaseline → upload",
	);
	console.log("  syncOne config-aware change detection OK");

	// --- fetchDecalImageId (offline; injected fetcher) ---
	console.log("Testing fetchDecalImageId...");

	const noWait = async () => {};
	const cdnLocation = JSON.stringify({ location: "https://cdn.example/abc" });

	// API キーがあれば Open Cloud 経由。JSON で場所を引いてから本体を取りに行く 2 ホップ
	const keyedCalls = [];
	assert.strictEqual(
		await fetchDecalImageId("123", {
			apiKey: "secret-key",
			wait: noWait,
			fetchAsset: async (url, headers) => {
				keyedCalls.push({ url, headers });
				return url.includes("cdn.example") ? decalXml : cdnLocation;
			},
		}),
		"555",
	);
	assert.strictEqual(keyedCalls.length, 2, "location lookup + asset body");
	assert.strictEqual(keyedCalls[0].url, "https://apis.roblox.com/asset-delivery-api/v1/assetId/123");
	assert.strictEqual(keyedCalls[0].headers["x-api-key"], "secret-key");
	assert.strictEqual(keyedCalls[1].url, "https://cdn.example/abc");

	// "rbxassetid://" 前置きも受け付ける
	assert.strictEqual(
		await fetchDecalImageId("rbxassetid://123", {
			wait: noWait,
			fetchAsset: async (url) => (url.includes("cdn.example") ? decalXml : cdnLocation),
		}),
		"555",
	);

	// Open Cloud が弾かれたら旧 assetdelivery にフォールバックする
	const fallbackCalls = [];
	assert.strictEqual(
		await fetchDecalImageId("123", {
			apiKey: "secret-key",
			wait: noWait,
			fetchAsset: async (url) => {
				fallbackCalls.push(url);
				if (url.includes("apis.roblox.com")) throw new Error("GET failed (403)");
				return url.includes("cdn.example") ? decalXml : cdnLocation;
			},
		}),
		"555",
	);
	assert.strictEqual(fallbackCalls.length, 3, "open cloud -> legacy -> cdn");
	assert(fallbackCalls[1].includes("assetdelivery.roblox.com"));

	// アップロード直後に配信が間に合わないケース: リトライで拾う
	let attemptCount = 0;
	assert.strictEqual(
		await fetchDecalImageId("123", {
			wait: noWait,
			fetchAsset: async (url) => {
				attemptCount++;
				if (attemptCount <= 2) throw new Error("GET failed (404)");
				return url.includes("cdn.example") ? decalXml : cdnLocation;
			},
		}),
		"555",
	);
	assert(attemptCount >= 3, "retried before succeeding");

	await assert.rejects(
		() => fetchDecalImageId("123", { attempts: 2, wait: noWait, fetchAsset: async () => "" }),
		/could not resolve the image id of decal 123/,
	);
	await assert.rejects(
		() =>
			fetchDecalImageId("123", {
				attempts: 1,
				wait: noWait,
				fetchAsset: async () => {
					throw new Error("boom");
				},
			}),
		/could not resolve the image id of decal 123: boom/,
	);
	await assert.rejects(() => fetchDecalImageId("not-an-id"), /invalid decal asset id: not-an-id/);
	console.log("  fetchDecalImageId OK");

	// --- fetchAssetContent (offline; injected fetcher) ---
	console.log("Testing fetchAssetContent...");

	const modelBody = Buffer.from("<roblox!\x89\xff\r\n\x1a\n\x00INSTcube\x00", "latin1");

	// Image ID 解決と同じ 2 ホップ。version を渡すと版指定の URL になる
	const contentCalls = [];
	const fetchedBody = await fetchAssetContent("rbxassetid://123", {
		apiKey: "secret-key",
		version: 3,
		wait: noWait,
		fetchAsset: async (url, headers) => {
			contentCalls.push({ url, headers });
			return url.includes("cdn.example") ? modelBody : cdnLocation;
		},
	});
	assert(Buffer.isBuffer(fetchedBody), "returns a Buffer");
	assert.strictEqual(fetchedBody.toString("latin1"), modelBody.toString("latin1"));
	assert.strictEqual(contentCalls[0].url, "https://apis.roblox.com/asset-delivery-api/v1/assetId/123/version/3");
	assert.strictEqual(contentCalls[0].headers["x-api-key"], "secret-key");
	assert.strictEqual(contentCalls[1].url, "https://cdn.example/abc");

	// Open Cloud が弾かれたら旧 assetdelivery へ落ちるのも同じ
	const contentFallback = [];
	const fallbackBody = await fetchAssetContent("123", {
		apiKey: "secret-key",
		wait: noWait,
		fetchAsset: async (url) => {
			contentFallback.push(url);
			if (url.includes("apis.roblox.com")) throw new Error("GET failed (401)");
			return url.includes("cdn.example") ? modelBody : cdnLocation;
		},
	});
	assert.strictEqual(fallbackBody.toString("latin1"), modelBody.toString("latin1"));
	assert.strictEqual(contentFallback.length, 3, "open cloud -> legacy -> cdn");

	await assert.rejects(
		() =>
			fetchAssetContent("123", {
				attempts: 1,
				wait: noWait,
				fetchAsset: async () => {
					throw new Error("boom");
				},
			}),
		/could not fetch the contents of asset 123: boom/,
	);
	await assert.rejects(() => fetchAssetContent("not-an-id"), /invalid asset id: not-an-id/);
	console.log("  fetchAssetContent OK");

	// --- syncOne image id backfill (offline) ---
	console.log("Testing syncOne image id backfill...");

	function makeBackfillDir(files) {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-backfill-test-"));
		const assetDir = path.join(dir, "assets", "images");
		fs.mkdirSync(assetDir, { recursive: true });
		const lockEntries = {};
		for (const [name, contents] of Object.entries(files)) {
			const filePath = path.join(assetDir, name);
			fs.writeFileSync(filePath, contents);
			lockEntries[name] = { assetId: name.replace(/\D/g, "") || "1", hash: fileHash(filePath) };
		}
		fs.writeFileSync(path.join(assetDir, "images.lock.json"), JSON.stringify(lockEntries, null, 2));
		return { dir, lockPath: path.join(assetDir, "images.lock.json") };
	}

	const backfillCreator = { type: "user", id: 12345 };
	const backfillSync = { name: "images", path: "assets/images" };

	// (1) 解決に失敗しても sync は落ちず、Decal ID のまま残る
	const failing = makeBackfillDir({ "1.png": "one" });
	await syncOne(backfillSync, backfillCreator, "unused-api-key", failing.dir, {
		resolveImageId: async () => {
			throw new Error("403");
		},
	});
	const failingLock = JSON.parse(fs.readFileSync(failing.lockPath, "utf8"));
	assert.strictEqual(failingLock["1.png"].assetId, "1", "failure keeps the decal id");
	assert.strictEqual(failingLock["1.png"].imageId, undefined, "failure records no imageId");

	// (2) resolveImageIds = false なら解決を試みない
	let optOutCalls = 0;
	const optOut = makeBackfillDir({ "1.png": "one" });
	await syncOne({ ...backfillSync, resolveImageIds: false }, backfillCreator, "unused-api-key", optOut.dir, {
		resolveImageId: async () => {
			optOutCalls++;
			return "999";
		},
	});
	assert.strictEqual(optOutCalls, 0, "resolveImageIds = false disables resolution");

	// (3) 連続失敗が続いたらグループの残りは諦める (全ファイルでリトライしない)
	let breakerCalls = 0;
	const breaker = makeBackfillDir({ "1.png": "a", "2.png": "b", "3.png": "c", "4.png": "d", "5.png": "e" });
	await syncOne(backfillSync, backfillCreator, "unused-api-key", breaker.dir, {
		resolveImageId: async () => {
			breakerCalls++;
			throw new Error("403");
		},
	});
	assert.strictEqual(breakerCalls, 3, "gives up after 3 consecutive failures");

	// (4) 音声など非画像は Decal ラッパーが無いので解決しない
	let audioCalls = 0;
	const audio = makeBackfillDir({ "1.mp3": "sound" });
	await syncOne(backfillSync, backfillCreator, "unused-api-key", audio.dir, {
		resolveImageId: async () => {
			audioCalls++;
			return "999";
		},
	});
	assert.strictEqual(audioCalls, 0, "non-image asset types are left alone");
	console.log("  syncOne image id backfill OK");

	// --- 変換される形式は allowConvertedFormats 無しでは skip される ---
	console.log("Testing converted-format skip...");

	function makeMeshDir() {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-mesh-test-"));
		const assetDir = path.join(dir, "assets", "meshes");
		fs.mkdirSync(assetDir, { recursive: true });
		fs.writeFileSync(path.join(assetDir, "cube.fbx"), "fbx bytes");
		return { dir, lockPath: path.join(assetDir, "meshes.lock.json") };
	}

	// アップロードを試みれば Open Cloud に出て落ちるので、空のロックが skip の証拠になる
	const bareMesh = makeMeshDir();
	await syncOne({ name: "meshes", path: "assets/meshes" }, backfillCreator, "unused-api-key", bareMesh.dir);
	assert.deepStrictEqual(
		JSON.parse(fs.readFileSync(bareMesh.lockPath, "utf8")),
		{},
		".fbx is skipped without allowConvertedFormats",
	);

	// assetType は「どの型で上げるか」であって許可ではないので、これだけでは通らない
	const typedMesh = makeMeshDir();
	await syncOne(
		{ name: "meshes", path: "assets/meshes", assetType: "Model" },
		backfillCreator,
		"unused-api-key",
		typedMesh.dir,
	);
	assert.deepStrictEqual(
		JSON.parse(fs.readFileSync(typedMesh.lockPath, "utf8")),
		{},
		'assetType = "Model" alone does not unlock .fbx',
	);
	console.log("  converted-format skip OK");

	// --- fetchAll (offline; injected content fetcher) ---
	console.log("Testing fetchAll...");

	function makeFetchDir(lockEntries) {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "rocas-fetch-test-"));
		const assetDir = path.join(dir, "assets", "images");
		fs.mkdirSync(assetDir, { recursive: true });
		fs.writeFileSync(path.join(assetDir, "images.lock.json"), JSON.stringify(lockEntries, null, 2));
		return { dir, assetDir };
	}

	const fetchConfig = { creator: backfillCreator, sync: [{ name: "images", path: "assets/images" }] };
	const pngBody = Buffer.from("\x89PNG\r\n\x1a\nbutton", "latin1");

	const cache = makeFetchDir({ "ui/button.png": { assetId: "111", imageId: "222", hash: "h1" } });
	const fetchIds = [];
	const recordingFetch = async (assetId) => {
		fetchIds.push(assetId);
		return pngBody;
	};

	const first = await fetchAll(fetchConfig, "secret-key", cache.dir, { fetchContent: recordingFetch });
	// 画像は Decal ID ではなく中身の Image ID を落とす (Decal を落としても画像は出てこない)
	assert.deepStrictEqual(fetchIds, ["222"], "prefers the image id");
	assert.strictEqual(first.fetched, 1);
	assert.strictEqual(first.reused, 0);
	assert.strictEqual(first.failed, 0);
	assert.strictEqual(path.relative(cache.dir, first.outDir), DEFAULT_FETCH_DIR, "defaults outside every synced path");
	assert.deepStrictEqual(
		fs.readFileSync(path.join(first.outDir, "222.png")),
		pngBody,
		"named by asset id + detected extension",
	);

	// 2 回目: lock が変わっていないので取り直さない
	const second = await fetchAll(fetchConfig, "secret-key", cache.dir, { fetchContent: recordingFetch });
	assert.deepStrictEqual(fetchIds, ["222"], "unchanged lock entries are not re-fetched");
	assert.strictEqual(second.reused, 1);

	// 落としたファイルが消えていれば取り直す
	fs.unlinkSync(path.join(first.outDir, "222.png"));
	const third = await fetchAll(fetchConfig, "secret-key", cache.dir, { fetchContent: async () => pngBody });
	assert.strictEqual(third.fetched, 1, "a missing local file is fetched again");

	// 1 つ失敗しても残りは続き、失敗数が返る
	const failingCache = makeFetchDir({ "a.png": { assetId: "1", hash: "h" }, "b.png": { assetId: "2", hash: "h" } });
	const failed = await fetchAll(fetchConfig, "secret-key", failingCache.dir, {
		fetchContent: async (assetId) => {
			if (assetId === "1") throw new Error("GET failed (403)");
			return pngBody;
		},
	});
	assert.strictEqual(failed.failed, 1);
	assert.strictEqual(failed.fetched, 1);

	// 知らないグループ名は黙って素通しさせない
	await assert.rejects(
		() => fetchAll(fetchConfig, "secret-key", cache.dir, { groups: ["nope"] }),
		/Unknown sync group\(s\): nope/,
	);

	// 出力先が sync の path の中だと警告する (次の sync が再アップロードしてしまうため)
	const warnings = [];
	const originalWarn = console.warn;
	console.warn = (message) => warnings.push(String(message));
	try {
		await fetchAll(fetchConfig, "secret-key", cache.dir, { out: "assets/images", fetchContent: async () => pngBody });
	} finally {
		console.warn = originalWarn;
	}
	assert(
		warnings.some((message) => message.includes("inside the synced path of images")),
		"warns when restoring into a synced path",
	);
	console.log("  fetchAll OK");

	console.log("\nAll tests passed!");
})().catch((error) => {
	console.error(error);
	process.exit(1);
});
