const { existsSync, readFileSync, writeFileSync, mkdirSync } = require("fs");
const path = require("path");
const { EXT_TO_ASSET_TYPE } = require("./sync");
const { assetIdString, normalizeAssetPath } = require("./asset-map");

const DEFAULT_PLUGIN_FILE_NAME = "rocas-studio-plugin.luau";

function inferAssetType(relPath, syncConfig) {
	if (syncConfig.assetType) {
		return syncConfig.assetType;
	}

	return EXT_TO_ASSET_TYPE[path.extname(relPath).toLowerCase()] || "Unknown";
}

function fileNameFromAssetPath(assetPath) {
	const parts = normalizeAssetPath(assetPath).split("/");
	return parts[parts.length - 1] || assetPath;
}

function buildStudioPluginManifest(config, cwd = process.cwd()) {
	const manifest = {
		generatedBy: "rocas",
		generatedAt: new Date().toISOString(),
		assets: [],
	};

	for (const syncConfig of config.sync || []) {
		const assetDir = path.resolve(cwd, syncConfig.path);
		const lockPath = path.join(assetDir, `${syncConfig.name}.lock.json`);

		if (!existsSync(lockPath)) {
			continue;
		}

		const lock = JSON.parse(readFileSync(lockPath, "utf8"));

		for (const [lockKey, entry] of Object.entries(lock)) {
			if (!entry || entry.assetId == null) {
				continue;
			}

			const assetPath = normalizeAssetPath(lockKey);
			const sourcePath = normalizeAssetPath(path.relative(cwd, path.resolve(assetDir, assetPath)));

			manifest.assets.push({
				group: syncConfig.name,
				path: assetPath,
				name: fileNameFromAssetPath(assetPath),
				sourcePath,
				assetId: assetIdString(entry.assetId),
				assetType: inferAssetType(assetPath, syncConfig),
			});
		}
	}

	manifest.assets.sort((a, b) => {
		const groupCompare = a.group.localeCompare(b.group);
		if (groupCompare !== 0) return groupCompare;
		return a.path.localeCompare(b.path);
	});

	return manifest;
}

function luaLongString(value) {
	for (let equals = 0; equals < 8; equals++) {
		const marker = "=".repeat(equals);
		const open = `[${marker}[`;
		const close = `]${marker}]`;
		if (!value.includes(close)) {
			return `${open}${value}${close}`;
		}
	}

	throw new Error("Unable to encode manifest as a Lua long string");
}

function generateStudioPlugin(manifest) {
	const manifestJson = JSON.stringify(manifest, null, 2);
	return STUDIO_PLUGIN_TEMPLATE.replace("__ROCAS_MANIFEST_JSON__", luaLongString(manifestJson));
}

function robloxStudioPluginsDir(env = process.env, platform = process.platform) {
	if (platform === "win32" && env.LOCALAPPDATA) {
		return path.join(env.LOCALAPPDATA, "Roblox", "Plugins");
	}

	if (env.HOME) {
		return path.join(env.HOME, "Documents", "Roblox", "Plugins");
	}

	return null;
}

function defaultStudioPluginOutputPath(cwd = process.cwd(), env = process.env, platform = process.platform) {
	const pluginsDir = robloxStudioPluginsDir(env, platform);
	return path.join(pluginsDir || cwd, DEFAULT_PLUGIN_FILE_NAME);
}

function resolveStudioPluginOutputPath(cwd = process.cwd(), outputPath) {
	if (outputPath) {
		return path.resolve(cwd, outputPath);
	}

	return defaultStudioPluginOutputPath(cwd);
}

function writeStudioPlugin(config, cwd = process.cwd(), outputPath) {
	const resolvedOutput = resolveStudioPluginOutputPath(cwd, outputPath);
	const manifest = buildStudioPluginManifest(config, cwd);
	const source = generateStudioPlugin(manifest);
	const outputDir = path.dirname(resolvedOutput);

	if (!existsSync(outputDir)) {
		mkdirSync(outputDir, { recursive: true });
	}

	writeFileSync(resolvedOutput, source);
	return resolvedOutput;
}

const STUDIO_PLUGIN_TEMPLATE = `-- This file is auto-generated by rocas. Do not edit manually.
-- Put it in the Roblox Studio local Plugins folder to use the asset browser.

local HttpService = game:GetService("HttpService")
local InsertService = game:GetService("InsertService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Selection = game:GetService("Selection")
local SoundService = game:GetService("SoundService")
local StarterGui = game:GetService("StarterGui")
local Workspace = game:GetService("Workspace")

local manifest = HttpService:JSONDecode(__ROCAS_MANIFEST_JSON__)
local assets = manifest.assets or {}

local toolbar = plugin:CreateToolbar("rocas")
local toggleButton = toolbar:CreateButton("Assets", "Browse rocas synced assets", "")
toggleButton.ClickableWhenViewportHidden = true

local widgetInfo = DockWidgetPluginGuiInfo.new(
	Enum.InitialDockState.Right,
	false,
	true,
	380,
	560,
	320,
	360
)

local widget = plugin:CreateDockWidgetPluginGui("rocasAssetBrowser", widgetInfo)
widget.Title = "rocas Assets"

local root = Instance.new("Frame")
root.Name = "Root"
root.Size = UDim2.fromScale(1, 1)
root.BackgroundColor3 = Color3.fromRGB(24, 26, 30)
root.BorderSizePixel = 0
root.Parent = widget

local rootPadding = Instance.new("UIPadding")
rootPadding.PaddingTop = UDim.new(0, 12)
rootPadding.PaddingRight = UDim.new(0, 12)
rootPadding.PaddingBottom = UDim.new(0, 12)
rootPadding.PaddingLeft = UDim.new(0, 12)
rootPadding.Parent = root

local layout = Instance.new("UIListLayout")
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Padding = UDim.new(0, 8)
layout.Parent = root

local header = Instance.new("TextLabel")
header.Name = "Header"
header.LayoutOrder = 1
header.Size = UDim2.new(1, 0, 0, 24)
header.BackgroundTransparency = 1
header.Font = Enum.Font.GothamBold
header.Text = "rocas Assets"
header.TextColor3 = Color3.fromRGB(244, 246, 248)
header.TextSize = 18
header.TextXAlignment = Enum.TextXAlignment.Left
header.Parent = root

local generatedAt = Instance.new("TextLabel")
generatedAt.Name = "GeneratedAt"
generatedAt.LayoutOrder = 2
generatedAt.Size = UDim2.new(1, 0, 0, 18)
generatedAt.BackgroundTransparency = 1
generatedAt.Font = Enum.Font.Gotham
generatedAt.Text = "Generated " .. tostring(manifest.generatedAt or "")
generatedAt.TextColor3 = Color3.fromRGB(150, 156, 166)
generatedAt.TextSize = 11
generatedAt.TextTruncate = Enum.TextTruncate.AtEnd
generatedAt.TextXAlignment = Enum.TextXAlignment.Left
generatedAt.Parent = root

local searchBox = Instance.new("TextBox")
searchBox.Name = "Search"
searchBox.LayoutOrder = 3
searchBox.Size = UDim2.new(1, 0, 0, 34)
searchBox.BackgroundColor3 = Color3.fromRGB(35, 38, 44)
searchBox.BorderSizePixel = 0
searchBox.ClearTextOnFocus = false
searchBox.Font = Enum.Font.Gotham
searchBox.PlaceholderText = "Search"
searchBox.PlaceholderColor3 = Color3.fromRGB(125, 132, 144)
searchBox.Text = ""
searchBox.TextColor3 = Color3.fromRGB(238, 241, 245)
searchBox.TextSize = 14
searchBox.TextXAlignment = Enum.TextXAlignment.Left
searchBox.Parent = root

local searchPadding = Instance.new("UIPadding")
searchPadding.PaddingLeft = UDim.new(0, 10)
searchPadding.PaddingRight = UDim.new(0, 10)
searchPadding.Parent = searchBox

local searchCorner = Instance.new("UICorner")
searchCorner.CornerRadius = UDim.new(0, 6)
searchCorner.Parent = searchBox

local filters = Instance.new("Frame")
filters.Name = "Filters"
filters.LayoutOrder = 4
filters.Size = UDim2.new(1, 0, 0, 28)
filters.BackgroundTransparency = 1
filters.Parent = root

local filterLayout = Instance.new("UIListLayout")
filterLayout.FillDirection = Enum.FillDirection.Horizontal
filterLayout.SortOrder = Enum.SortOrder.LayoutOrder
filterLayout.Padding = UDim.new(0, 6)
filterLayout.Parent = filters

local list = Instance.new("ScrollingFrame")
list.Name = "AssetList"
list.LayoutOrder = 5
list.Size = UDim2.new(1, 0, 1, -164)
list.BackgroundTransparency = 1
list.BorderSizePixel = 0
list.CanvasSize = UDim2.fromOffset(0, 0)
list.ScrollBarThickness = 6
list.AutomaticCanvasSize = Enum.AutomaticSize.None
list.Parent = root

local listLayout = Instance.new("UIListLayout")
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Padding = UDim.new(0, 8)
listLayout.Parent = list

local status = Instance.new("TextLabel")
status.Name = "Status"
status.LayoutOrder = 6
status.Size = UDim2.new(1, 0, 0, 20)
status.BackgroundTransparency = 1
status.Font = Enum.Font.Gotham
status.Text = ""
status.TextColor3 = Color3.fromRGB(158, 165, 176)
status.TextSize = 12
status.TextTruncate = Enum.TextTruncate.AtEnd
status.TextXAlignment = Enum.TextXAlignment.Left
status.Parent = root

local selectedType = "All"
local filterButtons = {}
local filterValues = {
	{ label = "All", value = "All", width = 40 },
	{ label = "Image", value = "Decal", width = 48 },
	{ label = "Audio", value = "Audio", width = 48 },
	{ label = "Model", value = "Model", width = 48 },
	{ label = "Anim", value = "Animation", width = 42 },
	{ label = "Video", value = "Video", width = 48 },
}

local typeColors = {
	Decal = Color3.fromRGB(54, 141, 214),
	Audio = Color3.fromRGB(77, 173, 96),
	Model = Color3.fromRGB(217, 145, 57),
	Animation = Color3.fromRGB(165, 110, 226),
	Video = Color3.fromRGB(216, 82, 103),
	Unknown = Color3.fromRGB(120, 126, 138),
}

local usageByAssetId = {}
local watchedScripts = {}
local watchedScriptCount = 0
local usageScanScheduled = false
local renderList

local function sanitizeName(value)
	local name = tostring(value or "Asset"):gsub("%.[^%.]+$", "")
	name = name:gsub("[^%w%s_%-]", "_")
	name = name:gsub("^%s+", ""):gsub("%s+$", "")
	if name == "" then
		return "rocas Asset"
	end
	return name
end

local function numericAssetId(assetId)
	return tonumber(tostring(assetId or ""):match("%d+"))
end

local function isScriptLike(instance)
	return instance:IsA("Script") or instance:IsA("LocalScript") or instance:IsA("ModuleScript")
end

local function readScriptSource(instance)
	local ok, source = pcall(function()
		return instance.Source
	end)

	if ok and type(source) == "string" then
		return source
	end

	return nil
end

local function assetSearchTokens(asset)
	local tokens = {}
	local seen = {}

	local function addToken(value)
		local token = tostring(value or "")
		if token ~= "" and not seen[token] then
			seen[token] = true
			table.insert(tokens, token)
		end
	end

	addToken(asset.assetId)
	addToken(numericAssetId(asset.assetId))
	addToken(asset.path)
	addToken(tostring(asset.path or ""):gsub("%.[^%.]+$", ""))
	addToken(asset.name)
	addToken(tostring(asset.name or ""):gsub("%.[^%.]+$", ""))

	return tokens
end

local searchTokensByAssetId = {}
for _, asset in ipairs(assets) do
	searchTokensByAssetId[asset.assetId] = assetSearchTokens(asset)
end

local function ensureFolder(parent, folderName)
	local existing = parent:FindFirstChild(folderName)
	if existing and existing:IsA("Folder") then
		return existing
	end

	local folder = Instance.new("Folder")
	folder.Name = folderName
	folder.Parent = parent
	return folder
end

local function ensureScreenGui(name)
	local existing = StarterGui:FindFirstChild(name)
	if existing and existing:IsA("ScreenGui") then
		return existing
	end

	local screenGui = Instance.new("ScreenGui")
	screenGui.Name = name
	screenGui.ResetOnSpawn = false
	screenGui.Parent = StarterGui
	return screenGui
end

local function selectedBasePart()
	for _, instance in ipairs(Selection:Get()) do
		if instance:IsA("BasePart") then
			return instance
		end

		local ancestor = instance:FindFirstAncestorWhichIsA("BasePart")
		if ancestor then
			return ancestor
		end
	end

	return nil
end

local function placeDecal(asset)
	local name = sanitizeName(asset.name or asset.path)
	local part = selectedBasePart()
	if part then
		local decal = Instance.new("Decal")
		decal.Name = name
		decal.Texture = asset.assetId
		decal.Face = Enum.NormalId.Front
		decal.Parent = part
		return decal
	end

	local screenGui = ensureScreenGui("rocas Images")
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = name
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = asset.assetId
	imageLabel.Size = UDim2.fromOffset(256, 256)
	imageLabel.Parent = screenGui
	return imageLabel
end

local function placeAudio(asset)
	local sound = Instance.new("Sound")
	sound.Name = sanitizeName(asset.name or asset.path)
	sound.SoundId = asset.assetId
	sound.Parent = SoundService
	return sound
end

local function placeAnimation(asset)
	local folder = ensureFolder(ReplicatedStorage, "rocas Animations")
	local animation = Instance.new("Animation")
	animation.Name = sanitizeName(asset.name or asset.path)
	animation.AnimationId = asset.assetId
	animation.Parent = folder
	return animation
end

local function placeVideo(asset)
	local screenGui = ensureScreenGui("rocas Videos")
	local videoFrame = Instance.new("VideoFrame")
	videoFrame.Name = sanitizeName(asset.name or asset.path)
	videoFrame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
	videoFrame.Size = UDim2.fromOffset(320, 180)
	videoFrame.Video = asset.assetId
	videoFrame.Parent = screenGui
	return videoFrame
end

local function placeModel(asset)
	local id = numericAssetId(asset.assetId)
	if not id then
		error("Invalid asset id")
	end

	local container = InsertService:LoadAsset(id)
	container.Name = sanitizeName(asset.name or asset.path)

	local children = container:GetChildren()
	if #children == 1 then
		local child = children[1]
		child.Name = container.Name
		child.Parent = Workspace
		container:Destroy()
		return child
	end

	container.Parent = Workspace
	return container
end

local function placeAsset(asset)
	if asset.assetType == "Decal" then
		return placeDecal(asset)
	elseif asset.assetType == "Audio" then
		return placeAudio(asset)
	elseif asset.assetType == "Animation" then
		return placeAnimation(asset)
	elseif asset.assetType == "Video" then
		return placeVideo(asset)
	elseif asset.assetType == "Model" then
		return placeModel(asset)
	end

	error("Unsupported asset type: " .. tostring(asset.assetType))
end

local function setStatus(message, isError)
	status.Text = message
	if isError then
		status.TextColor3 = Color3.fromRGB(239, 111, 111)
	else
		status.TextColor3 = Color3.fromRGB(158, 165, 176)
	end
end

local function matchesFilter(asset)
	if selectedType ~= "All" and asset.assetType ~= selectedType then
		return false
	end

	local query = string.lower(searchBox.Text or "")
	if query == "" then
		return true
	end

	local haystack = string.lower(table.concat({
		tostring(asset.group or ""),
		tostring(asset.path or ""),
		tostring(asset.name or ""),
		tostring(asset.assetId or ""),
		tostring(asset.assetType or ""),
	}, " "))

	return string.find(haystack, query, 1, true) ~= nil
end

local function sourceUsesAsset(source, asset)
	local tokens = searchTokensByAssetId[asset.assetId] or {}
	for _, token in ipairs(tokens) do
		if #token >= 4 and string.find(source, token, 1, true) then
			return true
		end
	end

	return false
end

local function rebuildUsage()
	local nextUsage = {}
	local nextWatchedScriptCount = 0

	for scriptInstance in pairs(watchedScripts) do
		if scriptInstance.Parent ~= nil then
			nextWatchedScriptCount = nextWatchedScriptCount + 1
			local source = readScriptSource(scriptInstance)

			if source and not string.find(source, "auto-generated by rocas", 1, true) then
				for _, asset in ipairs(assets) do
					if sourceUsesAsset(source, asset) then
						nextUsage[asset.assetId] = (nextUsage[asset.assetId] or 0) + 1
					end
				end
			end
		end
	end

	usageByAssetId = nextUsage
	watchedScriptCount = nextWatchedScriptCount
	renderList()
end

local function scheduleUsageScan()
	if usageScanScheduled then
		return
	end

	usageScanScheduled = true
	task.delay(0.2, function()
		usageScanScheduled = false
		rebuildUsage()
	end)
end

local function watchScript(instance)
	if not isScriptLike(instance) or watchedScripts[instance] then
		return
	end

	local ok, connection = pcall(function()
		return instance:GetPropertyChangedSignal("Source"):Connect(scheduleUsageScan)
	end)

	if ok and connection then
		watchedScripts[instance] = connection
		scheduleUsageScan()
	end
end

local function unwatchScript(instance)
	local connection = watchedScripts[instance]
	if not connection then
		return
	end

	connection:Disconnect()
	watchedScripts[instance] = nil
	scheduleUsageScan()
end

local function updateFilterButtons()
	for value, button in pairs(filterButtons) do
		local selected = value == selectedType
		if selected then
			button.BackgroundColor3 = Color3.fromRGB(232, 236, 242)
			button.TextColor3 = Color3.fromRGB(20, 22, 25)
		else
			button.BackgroundColor3 = Color3.fromRGB(35, 38, 44)
			button.TextColor3 = Color3.fromRGB(210, 215, 222)
		end
	end
end

local function clearRows()
	for _, child in ipairs(list:GetChildren()) do
		if child.Name == "AssetRow" then
			child:Destroy()
		end
	end
end

local function createRow(asset, index)
	local row = Instance.new("Frame")
	row.Name = "AssetRow"
	row.LayoutOrder = index
	row.Size = UDim2.new(1, -8, 0, 88)
	row.BackgroundColor3 = Color3.fromRGB(31, 34, 40)
	row.BorderSizePixel = 0
	row.Parent = list

	local rowCorner = Instance.new("UICorner")
	rowCorner.CornerRadius = UDim.new(0, 6)
	rowCorner.Parent = row

	local preview = Instance.new("Frame")
	preview.Name = "Preview"
	preview.Position = UDim2.fromOffset(10, 10)
	preview.Size = UDim2.fromOffset(56, 56)
	preview.BackgroundColor3 = typeColors[asset.assetType] or typeColors.Unknown
	preview.BorderSizePixel = 0
	preview.Parent = row

	local previewCorner = Instance.new("UICorner")
	previewCorner.CornerRadius = UDim.new(0, 6)
	previewCorner.Parent = preview

	if asset.assetType == "Decal" then
		local thumbnail = Instance.new("ImageLabel")
		thumbnail.Name = "Thumbnail"
		thumbnail.Size = UDim2.fromScale(1, 1)
		thumbnail.BackgroundTransparency = 1
		thumbnail.Image = asset.assetId
		thumbnail.ScaleType = Enum.ScaleType.Crop
		thumbnail.Parent = preview
	else
		local typeInitial = Instance.new("TextLabel")
		typeInitial.Name = "TypeInitial"
		typeInitial.Size = UDim2.fromScale(1, 1)
		typeInitial.BackgroundTransparency = 1
		typeInitial.Font = Enum.Font.GothamBold
		typeInitial.Text = string.sub(tostring(asset.assetType or "?"), 1, 1)
		typeInitial.TextColor3 = Color3.fromRGB(255, 255, 255)
		typeInitial.TextSize = 22
		typeInitial.Parent = preview
	end

	local title = Instance.new("TextLabel")
	title.Name = "Title"
	title.Position = UDim2.fromOffset(76, 9)
	title.Size = UDim2.new(1, -152, 0, 20)
	title.BackgroundTransparency = 1
	title.Font = Enum.Font.GothamBold
	title.Text = tostring(asset.name or asset.path or "Asset")
	title.TextColor3 = Color3.fromRGB(242, 245, 248)
	title.TextSize = 13
	title.TextTruncate = Enum.TextTruncate.AtEnd
	title.TextXAlignment = Enum.TextXAlignment.Left
	title.Parent = row

	local meta = Instance.new("TextLabel")
	meta.Name = "Meta"
	meta.Position = UDim2.fromOffset(76, 31)
	meta.Size = UDim2.new(1, -152, 0, 17)
	meta.BackgroundTransparency = 1
	meta.Font = Enum.Font.Gotham
	meta.Text = tostring(asset.group or "") .. " / " .. tostring(asset.path or "") .. " | Used in " .. tostring(usageByAssetId[asset.assetId] or 0)
	meta.TextColor3 = Color3.fromRGB(156, 164, 176)
	meta.TextSize = 11
	meta.TextTruncate = Enum.TextTruncate.AtEnd
	meta.TextXAlignment = Enum.TextXAlignment.Left
	meta.Parent = row

	local assetId = Instance.new("TextBox")
	assetId.Name = "AssetId"
	assetId.Position = UDim2.fromOffset(76, 52)
	assetId.Size = UDim2.new(1, -152, 0, 22)
	assetId.BackgroundColor3 = Color3.fromRGB(23, 25, 30)
	assetId.BorderSizePixel = 0
	assetId.ClearTextOnFocus = false
	assetId.Font = Enum.Font.Code
	assetId.Text = tostring(asset.assetId or "")
	assetId.TextColor3 = Color3.fromRGB(202, 209, 219)
	assetId.TextEditable = false
	assetId.TextSize = 11
	assetId.TextTruncate = Enum.TextTruncate.AtEnd
	assetId.TextXAlignment = Enum.TextXAlignment.Left
	assetId.Parent = row

	local assetIdPadding = Instance.new("UIPadding")
	assetIdPadding.PaddingLeft = UDim.new(0, 6)
	assetIdPadding.PaddingRight = UDim.new(0, 6)
	assetIdPadding.Parent = assetId

	local assetIdCorner = Instance.new("UICorner")
	assetIdCorner.CornerRadius = UDim.new(0, 4)
	assetIdCorner.Parent = assetId

	local typeBadge = Instance.new("TextLabel")
	typeBadge.Name = "Type"
	typeBadge.Position = UDim2.new(1, -68, 0, 10)
	typeBadge.Size = UDim2.fromOffset(58, 22)
	typeBadge.BackgroundColor3 = typeColors[asset.assetType] or typeColors.Unknown
	typeBadge.BorderSizePixel = 0
	typeBadge.Font = Enum.Font.GothamBold
	typeBadge.Text = tostring(asset.assetType or "Unknown")
	typeBadge.TextColor3 = Color3.fromRGB(255, 255, 255)
	typeBadge.TextSize = 10
	typeBadge.TextTruncate = Enum.TextTruncate.AtEnd
	typeBadge.Parent = row

	local badgeCorner = Instance.new("UICorner")
	badgeCorner.CornerRadius = UDim.new(0, 4)
	badgeCorner.Parent = typeBadge

	local insertButton = Instance.new("TextButton")
	insertButton.Name = "Insert"
	insertButton.Position = UDim2.new(1, -68, 1, -34)
	insertButton.Size = UDim2.fromOffset(58, 24)
	insertButton.BackgroundColor3 = Color3.fromRGB(232, 236, 242)
	insertButton.BorderSizePixel = 0
	insertButton.Font = Enum.Font.GothamBold
	insertButton.Text = "Insert"
	insertButton.TextColor3 = Color3.fromRGB(20, 22, 25)
	insertButton.TextSize = 12
	insertButton.Parent = row

	local insertCorner = Instance.new("UICorner")
	insertCorner.CornerRadius = UDim.new(0, 4)
	insertCorner.Parent = insertButton

	insertButton.MouseButton1Click:Connect(function()
		local ok, inserted = pcall(placeAsset, asset)
		if not ok then
			setStatus(tostring(inserted), true)
			return
		end

		if inserted then
			pcall(function()
				Selection:Set({ inserted })
			end)
		end

		setStatus("Inserted " .. tostring(asset.name or asset.path or "asset"), false)
	end)
end

function renderList()
	clearRows()

	local visible = 0
	for _, asset in ipairs(assets) do
		if matchesFilter(asset) then
			visible = visible + 1
			createRow(asset, visible)
		end
	end

	list.CanvasSize = UDim2.fromOffset(0, listLayout.AbsoluteContentSize.Y + 8)
	setStatus(tostring(visible) .. " of " .. tostring(#assets) .. " assets, watching " .. tostring(watchedScriptCount) .. " scripts", false)
end

for index, filter in ipairs(filterValues) do
	local value = filter.value
	local button = Instance.new("TextButton")
	button.Name = value
	button.LayoutOrder = index
	button.Size = UDim2.fromOffset(filter.width, 28)
	button.BackgroundColor3 = Color3.fromRGB(35, 38, 44)
	button.BorderSizePixel = 0
	button.Font = Enum.Font.GothamBold
	button.Text = filter.label
	button.TextColor3 = Color3.fromRGB(210, 215, 222)
	button.TextSize = 10
	button.Parent = filters

	local corner = Instance.new("UICorner")
	corner.CornerRadius = UDim.new(0, 6)
	corner.Parent = button

	filterButtons[value] = button

	button.MouseButton1Click:Connect(function()
		selectedType = value
		updateFilterButtons()
		renderList()
	end)
end

searchBox:GetPropertyChangedSignal("Text"):Connect(renderList)
listLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
	list.CanvasSize = UDim2.fromOffset(0, listLayout.AbsoluteContentSize.Y + 8)
end)

toggleButton.Click:Connect(function()
	widget.Enabled = not widget.Enabled
end)

for _, descendant in ipairs(game:GetDescendants()) do
	watchScript(descendant)
end

game.DescendantAdded:Connect(watchScript)
game.DescendantRemoving:Connect(unwatchScript)

updateFilterButtons()
renderList()
scheduleUsageScan()
`;

module.exports = {
	buildStudioPluginManifest,
	defaultStudioPluginOutputPath,
	generateStudioPlugin,
	luaLongString,
	resolveStudioPluginOutputPath,
	robloxStudioPluginsDir,
	writeStudioPlugin,
};
